# CloudPull GolangCI-Lint Configuration
# Comprehensive linting rules for Go code quality

run:
  # Timeout for analysis
  timeout: 5m
  
  # Include test files
  tests: true
  
  # Skip directories
  skip-dirs:
    - vendor
    - third_party
    - testdata
    - examples
    - build
  
  # Skip files
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"
  
  # Go version
  go: "1.21"

# Output configuration
output:
  # Format of output
  format: colored-line-number
  
  # Print lines of code with issue
  print-issued-lines: true
  
  # Print linter name in the end of issue text
  print-linter-name: true
  
  # Make issues output unique by line
  uniq-by-line: true

# Linter settings
linters-settings:
  # Error checking
  errcheck:
    # Report about not checking of errors in type assertions
    check-type-assertions: true
    
    # Report about assignment of errors to blank identifier
    check-blank: true
    
    # Exclude certain functions
    exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)

  # Go vet
  govet:
    # Report about shadowed variables
    check-shadowing: true
    
    # Settings per analyzer
    settings:
      printf:
        funcs:
          - (github.com/sirupsen/logrus.FieldLogger).Infof
          - (github.com/sirupsen/logrus.FieldLogger).Warnf
          - (github.com/sirupsen/logrus.FieldLogger).Errorf
          - (github.com/sirupsen/logrus.FieldLogger).Fatalf

  # Static analysis
  staticcheck:
    # SAxxxx checks
    checks: ["all"]

  # Style check
  stylecheck:
    # STxxxx checks
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
    
    # Check exported comments
    exported-fields-are-used: true

  # Unused variables
  unused:
    # Report exported fields that are unused
    check-exported: true

  # Variable naming
  varnamelen:
    # Maximum length of variable name
    max-distance: 6
    # Minimum length of variable name
    min-name-length: 2
    # Check method receivers
    check-receiver: true
    # Check return values
    check-return: true
    # Check type parameters
    check-type-param: true
    # Ignore commonly used names
    ignore-names:
      - err
      - id
      - ok
      - tt
      - db
      - tx
      - ctx

  # Cyclomatic complexity
  cyclop:
    # Maximum complexity
    max-complexity: 15
    # Package average complexity
    package-average: 10.0
    # Skip tests
    skip-tests: true

  # Function length
  funlen:
    # Maximum function length
    lines: 100
    # Maximum statements
    statements: 50
    # Ignore comments
    ignore-comments: true

  # Cognitive complexity
  gocognit:
    # Minimal cognitive complexity
    min-complexity: 20

  # Nested structs
  goconst:
    # Minimal length of string constant
    min-len: 3
    # Minimal occurrences count
    min-occurrences: 3

  # Imports
  goimports:
    # Put local imports after 3rd-party
    local-prefixes: github.com/VatsalSy/CloudPull

  # Line length
  lll:
    # Maximum line length
    line-length: 120
    # Tab width
    tab-width: 2

  # Misspell
  misspell:
    # Locale
    locale: US

  # Nesting depth
  nestif:
    # Maximum nesting depth
    min-complexity: 4

  # Whitespace
  whitespace:
    # Enforce multi-line if
    multi-if: true
    # Enforce multi-func
    multi-func: true

  # Error wrapping
  wrapcheck:
    # Packages to check for error wrapping
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
    ignorePackageGlobs:
      - github.com/VatsalSy/CloudPull/internal/errors

  # Documentation
  godox:
    # Keywords to check
    keywords:
      - TODO
      - BUG
      - FIXME
      - HACK
      - OPTIMIZE

  # Security
  gosec:
    # Exclude certain rules
    excludes:
      - G204 # Subprocess launched with variable
      - G304 # File path provided as taint input
    # Configure rules
    config:
      G306: "0600" # Expect file permissions

  # Duplication
  dupl:
    # Threshold
    threshold: 150

# Linters to enable
linters:
  enable:
    # Default linters
    - errcheck      # Error checking
    - gosimple      # Simplify code
    - govet         # Go vet
    - ineffassign   # Ineffectual assignments
    - staticcheck   # Static analysis
    - typecheck     # Type checking
    - unused        # Unused code
    
    # Additional linters
    - bodyclose     # HTTP response body closure
    - cyclop        # Cyclomatic complexity
    - dupl          # Code duplication
    - durationcheck # Duration multiplications
    - errorlint     # Error wrapping
    - exhaustive    # Exhaustive enum switches
    - exportloopref # Loop variable export
    - funlen        # Function length
    - gocognit      # Cognitive complexity
    - goconst       # Repeated strings
    - gocritic      # Opinionated checks
    - gocyclo       # Cyclomatic complexity
    - godot         # Comment periods
    - godox         # TODO/FIXME comments
    - gofmt         # Go fmt
    - goimports     # Import organization
    - gomnd         # Magic numbers
    - goprintffuncname # Printf func names
    - gosec         # Security
    - lll           # Line length
    - misspell      # Spelling
    - nakedret      # Naked returns
    - nestif        # Nested if statements
    - nilerr        # Return nil err
    - noctx         # HTTP without context
    - nolintlint    # Nolint directives
    - prealloc      # Slice preallocation
    - predeclared   # Shadowing predeclared
    - revive        # Configurable linter
    - rowserrcheck  # SQL rows.Err()
    - sqlclosecheck # SQL close checking
    - stylecheck    # Style checker
    - thelper       # Test helpers
    - tparallel     # Parallel tests
    - unconvert     # Unnecessary conversions
    - unparam       # Unused parameters
    - varnamelen    # Variable name length
    - whitespace    # Whitespace issues
    - wrapcheck     # Error wrapping

  disable:
    - depguard      # Dependencies guard
    - exhaustruct   # Exhaustive structs
    - forbidigo     # Forbidden identifiers
    - gochecknoglobals # No globals
    - gochecknoinits   # No init functions
    - goerr113      # Error variables
    - goheader      # File headers
    - golint        # Deprecated
    - gomodguard    # Module guard
    - interfacer    # Deprecated
    - maligned      # Deprecated
    - nlreturn      # New line returns
    - scopelint     # Deprecated
    - testpackage   # Separate test packages
    - wsl           # Whitespace linter

# Issues configuration
issues:
  # Exclude certain issues
  exclude-rules:
    # Exclude test files from certain linters
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - gocognit
        - goconst
        - gomnd
        - lll

    # Exclude example files
    - path: example.*\.go
      linters:
        - errcheck
        - ineffassign
        - noctx

    # Allow fmt.Printf in main
    - path: cmd/
      linters:
        - forbidigo

    # Allow magic numbers in test
    - path: _test\.go
      text: "Magic number"

  # Maximum issues per linter
  max-issues-per-linter: 50

  # Maximum same issues
  max-same-issues: 10

  # Exclude dirs from issues
  exclude-dirs:
    - vendor
    - third_party
    - testdata

  # Fix found issues
  fix: false