# Markdownlint configuration
# https://github.com/DavidAnson/markdownlint

default: true

# Line length
MD013:
  line_length: 120
  code_blocks: false
  tables: false

# Allow inline HTML
MD033: false

# Allow duplicate headings
MD024:
  siblings_only: true
